const Users = [
 {id:1,name:"Samandar",age:23,job:"Programmer",nation:"o'zbek",gender:"man"},
 {id:2,name:"Muhammad",age:14,job:"Student",nation:"o'zbek",gender:"man"},
 {id:3,name:"Abdulloh",age:10,job:"Student",nation:"o'zbek",gender:"man"},
 {id:4,name:"Alisher",age:53,job:"Teacher",nation:"o'zbek",gender:"man"},
 {id:5,name:"Fotima",age:53,job:"Teacher",nation:"o'zbek",gender:"woman"},
 {id:6,name:"Oydin",age:30,job:"housewife",nation:"o'zbek",gender:"woman"},
 {id:7,name:"Sadulla",age:33,job:"Driver",nation:"o'zbek",gender:"man"},
 {id:8,name:"Zarina",age:27,job:"housewife",nation:"o'zbek",gender:"woman"},
 {id:9,name:"O'tkir",age:30,job:"master",nation:"o'zbek",gender:"man"},
 {id:10,name:"Yusuf",age:50,job:"master",nation:"koreys",gender:"man"},
 {id:11,name:"Normurod",age:42,job:"Programmer",nation:"o'zbek",gender:"man"},
 {id:12,name:"Xadicha",age:16,job:"Student",nation:"koreys",gender:"woman"},
 {id:13,name:"Uldona",age:45,job:"Nurse",nation:"koreys",gender:"woman"},
 {id:14,name:"Odil",age:33,job:"Programmer",nation:"rus",gender:"man"},
 {id:15,name:"Baxtiyor",age:48,job:"Driver",nation:"rus",gender:"man"},
 {id:16,name:"Tulagan",age:41,job:"Menejer",nation:"rus",gender:"man"},
 {id:17,name:"Umarali",age:25,job:"Master",nation:"rus",gender:"man"},
 {id:18,name:"Hasan",age:19,job:"Student",nation:"rus",gender:"man"},
 {id:19,name:"Bobur",age:18,job:"Student",nation:"o'zbek",gender:"man"},
 {id:20,name:"Abdurasul",age:55,job:"Menejer",nation:"o'zbek",gender:"man"},
 {id:21,name:"Ilhom",age:47,job:"Master",nation:"o'zbek",gender:"man"},
 {id:22,name:"Javohir",age:21,job:"Student",nation:"o'zbek",gender:"man"},
 {id:23,name:"Sevara",age:20,job:"Student",nation:"rus",gender:"woman"},
];

module.exports = Users